In [2]:
import numpy as np

In [3]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0],[0],[0],[1]])

In [4]:
def sig(z):
    return 1/(1+np.exp(-z))

In [5]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))

In [6]:
weights = 2*np.random.random((2,1)) - 1
bias = 2*np.random.random((1)) - 1
learning_rate = 0.1
weights,bias

(array([[-0.37158832],
        [-0.29244312]]), array([0.20888989]))

In [11]:
for iter in range(10000):
    output0 = X
    output = sig(np.dot(output0,weights) + bias)

    first_term = output -Y
    input_from_last_layer = np.dot(output0,weights) + bias
    second_term = derivativeSig(input_from_last_layer)
    first_two = first_term*second_term
    first_two.shape

    changes_weight = np.array([[0.0],[0.0]])

    changes_weight = np.dot(output0.T,first_two)
    weights = weights - learning_rate*changes_weight

    bias_change = np.sum(first_two)
    bias = bias - learning_rate*bias_change

output = sig(np.dot(X,weights) + bias)
print(weights)
print(bias)
print(output)

[[6.26995954]
 [6.26995954]]
[-9.49476471]
[[7.52390672e-05]
 [3.82428569e-02]
 [3.82428569e-02]
 [9.54572865e-01]]
