In [1]:
import numpy as np

In [2]:
X = X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0],[1],[1],[0]])
X.shape,Y.shape

((4, 2), (4, 1))

In [3]:
def sig(z):
    return 1/(1+np.exp(-z))

In [4]:
def derivativeSig(z):
    return sig(z)*(1-sig(z))

In [5]:
weight_hidden = 2*np.random.random((2,2)) - 1
bias_hidden = 2*np.random.random((1,2)) - 1
weight_output = 2*np.random.random((2,1)) - 1
bias_output = 2*np.random.random((1)) - 1
learning_rate = 0.1

In [11]:
for iter in range(10000):
    output0 = X

    inputHidden = np.dot(output0,weight_hidden) + bias_hidden
    outputHidden = sig(inputHidden)
    inputForOutputLayer = np.dot(outputHidden,weight_output) + bias_output
    output = sig(inputForOutputLayer)

    first_term_output_layer = output - Y
    second_term_output_layer= derivativeSig(inputForOutputLayer)
    first_two_output_layer = first_term_output_layer*second_term_output_layer

    first_term_hidden_layer = np.dot(first_two_output_layer,weight_output.T)
    second_term_hidden_layer = derivativeSig(inputHidden)
    first_two_hidden_layer = first_term_hidden_layer*second_term_hidden_layer

    change_weight_output = np.dot(outputHidden.T,first_two_output_layer)
    change_bias_output = np.sum(first_two_output_layer,axis=0,keepdims=True)

    change_weight_hidden = np.dot(output0.T,first_two_hidden_layer)
    change_bias_hidden = np.sum(first_two_hidden_layer,axis=0,keepdims=True)

    weight_output = weight_output - learning_rate*change_weight_output
    bias_output = bias_output - learning_rate*change_bias_output

    weight_hidden = weight_hidden - learning_rate*change_weight_hidden
    bias_hidden = bias_hidden - learning_rate*change_bias_hidden
    
output0 = X

inputHidden = np.dot(output0,weight_hidden) + bias_hidden
outputHidden = sig(inputHidden)
inputForOutputLayer = np.dot(outputHidden,weight_output) + bias_output
output = sig(inputForOutputLayer)

print(output)
print('\n')
print(weight_hidden)
print('\n')
print(bias_hidden)
print('\n')
print(weight_output)
print('\n')
print(bias_output)
print('\n')

[[0.06806915]
 [0.92125627]
 [0.93891566]
 [0.05959569]]


[[ 4.79413613  5.19521249]
 [-4.58865205 -5.30882058]]


[[ 2.28183715 -2.92412262]]


[[-6.64728724]
 [ 6.96612766]]


[[3.05966798]]


